{"kind":"issue","data":{"callable":"rce_problem","callable_line":4,"message":"User controlled data may lead to remote code execution. Flow from @test.py:5:24-5:26 -> {UserControlled} to @test.py:6:11-6:12 -> {RemoteCodeExecution} detected.","traces":[{"name":"forward","roots":[{"root":{"filename":"test.py","line":5,"start":24,"end":26},"leaves":[{"leaf":{"kind":"UserControlled"}}]}]},{"name":"backward","roots":[{"root":{"filename":"test.py","line":6,"start":11,"end":12},"leaves":[{"leaf":{"kind":"RemoteCodeExecution"}}]}]}]}}
