{
  "kind": "issue",
  "data": {
    "callable": "qualifier.rce_problem",
    "callable_line": 4,
    "code": 5001,
    "line": 6,
    "start": 11,
    "end": 12,
    "filename": "test.py",
    "message":
      "Possible shell injection. Data from [UserControlled] source(s) may reach [RemoteCodeExecution] sink(s)",
    "traces": [
      {
        "name": "forward",
        "roots": [
          {
            "root": {
              "filename": "test.py",
              "line": 5,
              "start": 24,
              "end": 26
            },
            "leaves": [ { "kind": "UserControlled" } ]
          }
        ]
      },
      {
        "name": "backward",
        "roots": [
          {
            "root": {
              "filename": "test.py",
              "line": 6,
              "start": 10,
              "end": 13
            },
            "leaves": [ { "kind": "RemoteCodeExecution" } ]
          }
        ]
      }
    ]
  }
}
{
  "kind": "issue",
  "data": {
    "callable": "qualifier.subprocess_problem",
    "callable_line": 9,
    "code": 5001,
    "line": 11,
    "start": 26,
    "end": 27,
    "filename": "test.py",
    "message":
      "Possible shell injection. Data from [UserControlled] source(s) may reach [RemoteCodeExecution] sink(s)",
    "traces": [
      {
        "name": "forward",
        "roots": [
          {
            "root": {
              "filename": "test.py",
              "line": 10,
              "start": 24,
              "end": 26
            },
            "leaves": [ { "kind": "UserControlled" } ]
          }
        ]
      },
      {
        "name": "backward",
        "roots": [
          {
            "root": {
              "filename": "test.py",
              "line": 11,
              "start": 25,
              "end": 40
            },
            "leaves": [ { "kind": "RemoteCodeExecution" } ]
          }
        ]
      }
    ]
  }
}
