{"kind":"issue","data":{"callable":"rce_problem","callable_line":4,"message":"Possible shell injection. Data from [UserControlled] source(s) may reach [RemoteCodeExecution] sink(s)","traces":[{"name":"forward","roots":[{"root":{"filename":"test.py","line":5,"start":24,"end":26},"leaves":[{"leaf":{"kind":"UserControlled"}}]}]},{"name":"backward","roots":[{"root":{"filename":"test.py","line":6,"start":11,"end":12},"leaves":[{"leaf":{"kind":"RemoteCodeExecution"}}]}]}]}}
